'use client';

import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, RefreshCw, TrendingUp } from 'lucide-react';
import { apiFetch, ApiError } from '@/lib/api';

type Product = { id: string; name: string; type: string; status: string; statusReason: string };
type Row = Record<string, unknown> & { id?: string; status?: string; name?: string; event_type?: string; recommendation_type?: string; lifecycle_state?: string; evidence_reference?: string; occurred_at?: string; created_at?: string };
type Overview = { lifecycle: Row[]; recommendations: Row[]; campaigns: Row[]; messages: Row[]; segments: Row[]; experiments: Row[]; attribution: Row[]; events: Row[]; providerStates: Record<string, string> };

function value(input: unknown): string { return input === null || input === undefined || input === '' ? 'unavailable' : String(input).replaceAll('_', ' '); }
function Empty({ children }: { children: string }) { return <div className="rounded-xl border border-dashed border-[var(--card-border)] p-5 text-sm text-[var(--muted)]">{children}</div>; }
function EvidenceRows({ rows, primary }: { rows: Row[]; primary: keyof Row }) {
  if (!rows.length) return <Empty>No durable records are available.</Empty>;
  return <div className="divide-y divide-[var(--card-border)] rounded-xl border border-[var(--card-border)]">{rows.slice(0, 20).map((row, index) => <div key={row.id ?? index} className="flex flex-wrap items-center justify-between gap-2 p-3 text-sm"><span className="font-medium">{value(row[primary])}</span><span className="text-xs text-[var(--muted)]">{value(row.status ?? row.evidence_reference ?? row.occurred_at ?? row.created_at)}</span></div>)}</div>;
}

export default function GrowthCentreClient() {
  const [products, setProducts] = useState<Product[]>([]); const [projectId, setProjectId] = useState<string | null>(null);
  const [overview, setOverview] = useState<Overview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const loadProducts = useCallback(async () => { setLoading(true); setError(null); try { const data = await apiFetch<{ products: Product[] }>('/api/operations/portfolio?limit=100&offset=0'); setProducts(data.products ?? []); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Growth portfolio is unavailable'); } finally { setLoading(false); } }, []);
  const load = useCallback(async (id: string) => { setLoading(true); setError(null); try { setOverview(await apiFetch<Overview>(`/api/growth/overview?projectId=${encodeURIComponent(id)}`)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Growth evidence is unavailable'); } finally { setLoading(false); } }, []);
  useEffect(() => { void loadProducts(); }, [loadProducts]); useEffect(() => { if (projectId) void load(projectId); }, [projectId, load]);
  async function evaluate(kind: 'activation'|'recommendation') { if (!projectId) return; setBusy(true); setError(null); try { if (kind === 'activation') await apiFetch('/api/growth/activation/evaluate', { method: 'POST', body: JSON.stringify({ projectId }) }); else await apiFetch('/api/growth/recommendations/evaluate', { method: 'POST', body: JSON.stringify({ projectId, consent: false }) }); await load(projectId); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Evaluation failed'); } finally { setBusy(false); } }
  if (!projectId) return <main className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6"><header><h1 className="flex items-center gap-2 text-2xl font-bold"><TrendingUp className="h-6 w-6" />Growth Centre</h1><p className="mt-1 text-sm text-[var(--muted)]">Growth state is derived from real product, lifecycle, operations, consent, and delivery evidence.</p></header>{error && <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm"><AlertTriangle className="mr-2 inline h-4 w-4" />{error}</div>}{loading ? <p className="text-sm text-[var(--muted)]">Loading authorised products…</p> : products.length ? <div className="grid gap-3 md:grid-cols-2">{products.map((product) => <button key={product.id} onClick={() => setProjectId(product.id)} className="rounded-xl border border-[var(--card-border)] p-4 text-left hover:border-[var(--accent)]"><div className="font-semibold">{product.name}</div><div className="mt-1 text-xs text-[var(--muted)]">{product.type} · {value(product.status)} · {product.statusReason}</div></button>)}</div> : <Empty>No authorised product exists. Define a product before growth evaluation.</Empty>}</main>;
  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><button onClick={() => { setProjectId(null); setOverview(null); }} className="mb-2 inline-flex items-center gap-1 text-xs text-[var(--muted)]"><ArrowLeft className="h-3 w-3" />Portfolio</button><h1 className="text-2xl font-bold">Evidence-backed growth</h1></div><div className="flex gap-2"><button disabled={busy} onClick={() => evaluate('activation')} className="rounded-lg border border-[var(--card-border)] px-3 py-2 text-xs">Evaluate activation</button><button disabled={busy} onClick={() => evaluate('recommendation')} className="rounded-lg bg-[var(--foreground)] px-3 py-2 text-xs text-[var(--background)]">Next safe action</button><button aria-label="Refresh" onClick={() => load(projectId)} className="rounded-lg border border-[var(--card-border)] p-2"><RefreshCw className="h-4 w-4" /></button></div></header>{error && <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm"><AlertTriangle className="mr-2 inline h-4 w-4" />{error}</div>}{loading || !overview ? <p className="text-sm text-[var(--muted)]">Loading verified growth state…</p> : <><section><h2 className="mb-2 font-semibold">Lifecycle and activation</h2><EvidenceRows rows={overview.lifecycle} primary="lifecycle_state" /></section><section><h2 className="mb-2 font-semibold">Recommendations</h2><EvidenceRows rows={overview.recommendations} primary="recommendation_type" /></section><div className="grid gap-5 lg:grid-cols-2"><section><h2 className="mb-2 font-semibold">Campaigns and messages</h2><EvidenceRows rows={[...overview.campaigns, ...overview.messages]} primary="status" /></section><section><h2 className="mb-2 font-semibold">Experiments and attribution</h2><EvidenceRows rows={[...overview.experiments, ...overview.attribution]} primary="status" /></section></div><section><h2 className="mb-2 font-semibold">Canonical events</h2><EvidenceRows rows={overview.events} primary="event_type" /></section><section className="rounded-xl border border-[var(--card-border)] p-4"><h2 className="mb-3 flex items-center gap-2 font-semibold"><CheckCircle2 className="h-4 w-4" />Provider truth</h2><div className="grid gap-2 sm:grid-cols-3">{Object.entries(overview.providerStates).map(([provider, status]) => <div key={provider} className="rounded-lg bg-[var(--muted)]/10 p-3 text-sm"><div className="font-medium">{provider}</div><div className="text-xs text-[var(--muted)]">{value(status)}</div></div>)}</div></section></>}</main>;
}
