import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { CopyCodeButton } from '@/components/docs/CopyCodeButton';
import { Logo } from '@/components/layout/Logo';
import { DOC_PAGES, getDoc } from '@/lib/docsContent';
import { buildMetadata } from '@/lib/seo';

export function generateStaticParams() { return DOC_PAGES.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const page = getDoc((await params).slug); return page ? buildMetadata({ title: `${page.title} — Xroga Docs`, description: page.description, path: `/docs/${page.slug}` }) : {}; }
export default async function DocArticle({ params }: { params: Promise<{ slug: string }> }) { const page = getDoc((await params).slug); if (!page) notFound(); const index = DOC_PAGES.findIndex((item) => item.slug === page.slug); const previous = DOC_PAGES[index - 1]; const next = DOC_PAGES[index + 1]; const jsonLd = { '@context': 'https://schema.org', '@type': 'TechArticle', headline: page.title, description: page.description, dateModified: page.updated, author: { '@type': 'Organization', name: 'Xroga AI' }, mainEntityOfPage: `https://xroga.com/docs/${page.slug}` }; return <main className="min-h-screen bg-[var(--surface-page)] text-[var(--text-primary)]"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><header className="border-b border-[var(--border-subtle)]"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3"><Logo href="/" height={38} /><Link href="/docs" className="text-sm font-bold">All docs</Link></div></header><article className="mx-auto max-w-3xl px-4 py-10 sm:py-14"><nav aria-label="Breadcrumb" className="text-xs text-[var(--text-muted)]"><Link href="/">Xroga</Link> / <Link href="/docs">Docs</Link> / <span>{page.title}</span></nav><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">{page.title}</h1><p className="mt-4 text-lg leading-8 text-[var(--text-secondary)]">{page.description}</p><p className="mt-3 text-xs text-[var(--text-muted)]">Updated {page.updated} · <Link href={page.sourceHref} className="font-bold text-[var(--accent)]">Relevant product surface</Link></p><div className="mt-10 space-y-10">{page.sections.map((section) => <section key={section.heading}><h2 className="text-2xl font-black tracking-tight">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-3 leading-8 text-[var(--text-secondary)]">{paragraph}</p>)}{section.steps && <ol className="mt-4 list-decimal space-y-2 pl-5 text-[var(--text-secondary)]">{section.steps.map((step) => <li key={step}>{step}</li>)}</ol>}{section.code && <div className="relative mt-4 overflow-hidden rounded-xl bg-slate-950 p-4 pr-12 text-sm text-cyan-100"><CopyCodeButton value={section.code} /><code className="whitespace-pre-wrap">{section.code}</code></div>}</section>)}</div><nav aria-label="Documentation pagination" className="mt-12 grid grid-cols-2 gap-3 border-t border-[var(--border-subtle)] pt-6">{previous ? <Link href={`/docs/${previous.slug}`} className="rounded-xl border border-[var(--border-subtle)] p-3 text-sm">← {previous.title}</Link> : <span />}{next && <Link href={`/docs/${next.slug}`} className="rounded-xl border border-[var(--border-subtle)] p-3 text-right text-sm">{next.title} →</Link>}</nav></article></main>; }
