import { Router } from 'express';
import { z } from 'zod';
import type { AuthRequest } from '../middleware/auth.js';
import { exportTemplateToRepo, ExportError } from '../services/showcase/templateExport.js';
import { isShowcaseTemplateId, normalizeTargetDirectory } from '../services/showcase/templateSources.js';

const router = Router();

/**
 * Branch names are generated by the client from a template slug and project id.
 * Re-validate the shape here so a hand-crafted request cannot inject a ref.
 */
const BRANCH_RE = /^xroga\/template-[a-z0-9-]{1,40}-[a-z0-9]{1,8}$/;

/** GitHub's own owner/name character set — nothing here may reach a URL path unchecked. */
const REPO_RE = /^[A-Za-z0-9._-]{1,39}\/[A-Za-z0-9._-]{1,100}$/;

/**
 * A base branch is caller-chosen, so it is bounded to ref-safe characters. Git
 * forbids `..`, leading/trailing slashes, and `~^:?*[\` in ref names.
 */
const BASE_BRANCH_RE = /^[A-Za-z0-9._\-\/]{1,120}$/;

export const exportSchema = z
  .object({
    templateId: z.string().min(1).max(64),
    repoFullName: z.string().min(3).max(140).regex(REPO_RE),
    branch: z.string().min(1).max(120).regex(BRANCH_RE),
    projectName: z.string().min(1).max(120),
    userPrompt: z.string().max(8000).optional(),
    targetDirectory: z.string().max(200).optional(),
    baseBranch: z
      .string()
      .max(120)
      .regex(BASE_BRANCH_RE)
      .refine((value) => !value.includes('..') && !value.startsWith('/') && !value.endsWith('/'), {
        message: 'Invalid base branch',
      })
      .optional(),
  })
  .strict();

router.post('/export', async (req: AuthRequest, res) => {
  const parsed = exportSchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: 'Invalid export request' });
    return;
  }
  const body = parsed.data;

  if (!isShowcaseTemplateId(body.templateId)) {
    res.status(400).json({ error: 'Unknown template' });
    return;
  }
  if (!BRANCH_RE.test(body.branch)) {
    res.status(400).json({ error: 'Invalid branch name' });
    return;
  }
  if (normalizeTargetDirectory(body.targetDirectory) === null) {
    res.status(400).json({ error: 'Target directory is not allowed' });
    return;
  }

  try {
    const result = await exportTemplateToRepo({
      userId: req.userId!,
      templateId: body.templateId,
      repoFullName: body.repoFullName,
      branch: body.branch,
      projectName: body.projectName,
      userPrompt: body.userPrompt,
      targetDirectory: body.targetDirectory,
      baseBranch: body.baseBranch,
    });
    res.json(result);
  } catch (error) {
    if (error instanceof ExportError) {
      res.status(error.status).json({ error: error.message, code: error.code });
      return;
    }
    // Never leak provider internals to the browser.
    console.error('Showcase export failed', {
      category: 'showcase_export_error',
      userId: req.userId,
      templateId: body.templateId,
    });
    res.status(500).json({ error: 'Export failed. Please try again.' });
  }
});

export default router;
