// Generated by scripts/generate-capability-index.mjs. Do not hand-edit.
import { publicResearchCapability } from './modules/publicResearch.js';
import { repositoryReadCapability } from './modules/repositoryRead.js';
import { repositoryWriteCapability } from './modules/repositoryWrite.js';
import { softwareImplementCapability } from './modules/softwareImplement.js';
import { validationRunCapability } from './modules/validationRun.js';

export const generatedCapabilities = [
  publicResearchCapability,
  repositoryReadCapability,
  repositoryWriteCapability,
  softwareImplementCapability,
  validationRunCapability,
] as const;
