/**
 * The deterministic static site fallback.
 *
 * This is what a user receives when every builder provider returns empty,
 * prose-only or invalid output. It has to be a real page, not a stub: the previous
 * static scaffold emitted `<h1>{projectName}</h1>` with a zero-byte stylesheet and
 * a zero-byte script, which deploys but is not a product.
 *
 * Everything here is derived from the prompt with pure string work — no model call,
 * no network, no randomness, no clock. That matters twice over: the fallback must
 * work precisely when providers do not, and a worker restart must regenerate the
 * identical tree so a resumed run does not diverge from its checkpoint.
 *
 * It is deliberately modest. The goal is a valid, themed, buildable foundation that
 * the install/validate and shipping stages can carry to a live URL, and that a
 * healthy provider can later enhance — not a pretend implementation of whatever the
 * user asked for. Nothing here claims to be more than it is.
 */

export type SiteTheme = 'dark' | 'light';

export interface DeterministicSite {
  readonly title: string;
  readonly tagline: string;
  readonly theme: SiteTheme;
  readonly sections: readonly string[];
  readonly html: string;
  readonly css: string;
  readonly js: string;
}

/** Words that mean "make it dark" in an ordinary product prompt. */
const DARK_HINTS = ['dark', 'night', 'midnight', 'black', 'noir'];
const LIGHT_HINTS = ['light mode', 'light theme', 'bright', 'white theme', 'minimal white'];

/** Section words worth turning into real page sections when the prompt mentions them. */
const SECTION_HINTS: ReadonlyArray<readonly [RegExp, string]> = [
  [/\babout\b/i, 'About'],
  [/\bwork|portfolio|project/i, 'Work'],
  [/\bservice|offer/i, 'Services'],
  [/\bmenu\b/i, 'Menu'],
  [/\bprice|pricing|plan/i, 'Pricing'],
  [/\bteam\b/i, 'Team'],
  [/\bblog|article|post/i, 'Blog'],
  [/\bgallery|photo|image/i, 'Gallery'],
  [/\bfaq|question/i, 'FAQ'],
  [/\bcontact|email|reach/i, 'Contact'],
];

export function detectTheme(prompt: string): SiteTheme {
  const lower = prompt.toLowerCase();
  if (LIGHT_HINTS.some((hint) => lower.includes(hint))) return 'light';
  return DARK_HINTS.some((hint) => new RegExp(`\\b${hint}\\b`).test(lower)) ? 'dark' : 'light';
}

/**
 * A human title from the prompt.
 *
 * Strips the instruction verb so "Build a portfolio website for Sam" becomes
 * "Portfolio Website For Sam" rather than "Build A Portfolio Website For Sam".
 */
export function titleFromPrompt(prompt: string, fallback: string): string {
  const cleaned = prompt
    .replace(/^\s*(please\s+)?(build|create|make|generate|design|develop)\s+(me\s+)?(a|an|the)?\s*/i, '')
    .replace(/\bwith\b[\s\S]*$/i, '')
    .replace(/[.!?].*$/s, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (!cleaned) return fallback;
  const words = cleaned.split(' ').slice(0, 6);
  return words
    .map((word) => (word.length > 2 ? word[0].toUpperCase() + word.slice(1) : word))
    .join(' ');
}

export function sectionsFromPrompt(prompt: string): string[] {
  const found = SECTION_HINTS.filter(([pattern]) => pattern.test(prompt)).map(([, label]) => label);
  // Always give the page somewhere to go; a nav with one link is not a page.
  const base = found.length >= 2 ? found : ['About', ...found.filter((s) => s !== 'About'), 'Contact'];
  return [...new Set(base)].slice(0, 5);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/**
 * Builds the site.
 *
 * The prompt is echoed once, in the README and as the page's own description, so
 * the delivered project records what was asked for. It is escaped everywhere it
 * reaches HTML — a prompt is user input, and this file writes a real page.
 */
export function buildDeterministicSite(opts: {
  prompt: string;
  projectName: string;
}): DeterministicSite {
  const title = titleFromPrompt(opts.prompt, opts.projectName);
  const theme = detectTheme(opts.prompt);
  const sections = sectionsFromPrompt(opts.prompt);
  const tagline = 'A starting point generated by Xroga, ready to edit and extend.';

  const nav = sections
    .map((section) => `        <a href="#${slug(section)}">${escapeHtml(section)}</a>`)
    .join('\n');

  const blocks = sections
    .map(
      (section) => `      <section id="${slug(section)}" class="section">
        <h2>${escapeHtml(section)}</h2>
        <p>This section is part of the generated starting point. Replace this copy with your own ${escapeHtml(
          section.toLowerCase(),
        )} content.</p>
      </section>`,
    )
    .join('\n\n');

  const html = `    <header class="site-header">
      <a class="brand" href="#top">${escapeHtml(title)}</a>
      <nav class="site-nav">
${nav}
      </nav>
      <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav-links">Menu</button>
    </header>

    <main id="top">
      <section class="hero">
        <h1>${escapeHtml(title)}</h1>
        <p class="lede">${escapeHtml(tagline)}</p>
        <a class="cta" href="#${slug(sections[0] ?? 'about')}">Get started</a>
      </section>

${blocks}
    </main>

    <footer class="site-footer">
      <p>${escapeHtml(title)}</p>
    </footer>`;

  const dark = theme === 'dark';
  const css = `:root {
  --bg: ${dark ? '#0b0d10' : '#ffffff'};
  --surface: ${dark ? '#14181d' : '#f5f7fa'};
  --text: ${dark ? '#f2f5f8' : '#14181d'};
  --muted: ${dark ? '#9aa7b4' : '#54616e'};
  --border: ${dark ? '#242b33' : '#dfe4ea'};
  --accent: ${dark ? '#7cc4ff' : '#0a63d8'};
  --accent-ink: ${dark ? '#06121f' : '#ffffff'};
  --radius: 10px;
  --max: 1080px;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  line-height: 1.6;
}

a { color: var(--accent); }

.site-header {
  display: flex;
  align-items: center;
  gap: 1.5rem;
  width: min(var(--max), calc(100% - 2.5rem));
  margin: 0 auto;
  padding: 1.25rem 0;
  border-bottom: 1px solid var(--border);
}

.brand { font-weight: 700; text-decoration: none; color: var(--text); }

.site-nav { display: none; gap: 1.25rem; margin-left: auto; }
.site-nav a { text-decoration: none; color: var(--muted); }
.site-nav a:hover { color: var(--text); }
.site-nav.is-open { display: flex; flex-direction: column; position: absolute; top: 4rem; right: 1.25rem; padding: 1rem; background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); }

.nav-toggle {
  margin-left: auto;
  min-height: 40px;
  padding: 0.5rem 0.9rem;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--surface);
  color: var(--text);
  cursor: pointer;
}

@media (min-width: 720px) {
  .site-nav { display: flex; }
  .nav-toggle { display: none; }
}

main { width: min(var(--max), calc(100% - 2.5rem)); margin: 0 auto; }

.hero { padding: 4rem 0 3rem; }
.hero h1 { margin: 0; font-size: clamp(2rem, 5vw, 3rem); line-height: 1.1; }
.lede { max-width: 52ch; color: var(--muted); font-size: 1.05rem; }

.cta {
  display: inline-block;
  margin-top: 1.25rem;
  padding: 0.75rem 1.25rem;
  border-radius: var(--radius);
  background: var(--accent);
  color: var(--accent-ink);
  font-weight: 600;
  text-decoration: none;
}
.cta:focus-visible, .nav-toggle:focus-visible, .site-nav a:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}

.section {
  padding: 2rem 0;
  border-top: 1px solid var(--border);
}
.section h2 { margin: 0 0 0.5rem; font-size: 1.35rem; }
.section p { margin: 0; max-width: 60ch; color: var(--muted); }

.site-footer {
  width: min(var(--max), calc(100% - 2.5rem));
  margin: 3rem auto 0;
  padding: 1.5rem 0;
  border-top: 1px solid var(--border);
  color: var(--muted);
  font-size: 0.9rem;
}

@media (prefers-reduced-motion: reduce) {
  * { scroll-behavior: auto !important; }
}
`;

  const js = `// Mobile navigation. Kept dependency-free so the page works as plain static files.
(function () {
  var toggle = document.querySelector('.nav-toggle');
  var nav = document.querySelector('.site-nav');
  if (!toggle || !nav) return;

  nav.id = nav.id || 'site-nav-links';

  toggle.addEventListener('click', function () {
    var open = nav.classList.toggle('is-open');
    toggle.setAttribute('aria-expanded', String(open));
  });

  // Close after following an in-page link, so the panel does not cover the target.
  nav.addEventListener('click', function (event) {
    if (event.target instanceof HTMLAnchorElement) {
      nav.classList.remove('is-open');
      toggle.setAttribute('aria-expanded', 'false');
    }
  });
})();
`;

  return { title, tagline, theme, sections, html, css, js };
}
