-- Step 3 — Project Runtime Platform
--
-- Durable project revisions, long-lived project runtime sessions,
-- runtime events and encrypted project-scoped secrets.
--
-- Generated code still runs in the separate Xroga sandbox app.
-- None of these tables execute code.

CREATE TABLE IF NOT EXISTS public.project_runtime_revisions (
  revision_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  user_id UUID NOT NULL
    REFERENCES auth.users(id)
    ON DELETE CASCADE,

  project_id TEXT NOT NULL,
  run_id TEXT NOT NULL,

  revision_number BIGINT
    GENERATED BY DEFAULT AS IDENTITY,

  workspace_fingerprint TEXT NOT NULL,

  software_project JSONB NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_project_runtime_revisions_project
  ON public.project_runtime_revisions(
    user_id,
    project_id,
    revision_number DESC
  );

CREATE INDEX IF NOT EXISTS idx_project_runtime_revisions_run
  ON public.project_runtime_revisions(
    user_id,
    run_id
  );


CREATE TABLE IF NOT EXISTS public.project_runtime_sessions (
  session_id TEXT PRIMARY KEY,

  user_id UUID NOT NULL
    REFERENCES auth.users(id)
    ON DELETE CASCADE,

  project_id TEXT NOT NULL,

  provider_id TEXT NOT NULL,

  runtime_class TEXT NOT NULL CHECK (
    runtime_class IN (
      'interactive',
      'verification'
    )
  ),

  status TEXT NOT NULL CHECK (
    status IN (
      'creating',
      'running',
      'stopped',
      'failed',
      'destroyed'
    )
  ),

  state JSONB NOT NULL,

  expires_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_project_runtime_sessions_project
  ON public.project_runtime_sessions(
    user_id,
    project_id,
    updated_at DESC
  );


CREATE TABLE IF NOT EXISTS public.project_runtime_events (
  event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  user_id UUID NOT NULL
    REFERENCES auth.users(id)
    ON DELETE CASCADE,

  project_id TEXT NOT NULL,
  session_id TEXT,

  event_type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_project_runtime_events_project
  ON public.project_runtime_events(
    user_id,
    project_id,
    created_at DESC
  );

CREATE INDEX IF NOT EXISTS idx_project_runtime_events_session
  ON public.project_runtime_events(
    user_id,
    session_id,
    created_at ASC
  );


CREATE TABLE IF NOT EXISTS public.project_runtime_secrets (
  user_id UUID NOT NULL
    REFERENCES auth.users(id)
    ON DELETE CASCADE,

  project_id TEXT NOT NULL,

  name TEXT NOT NULL,

  scope TEXT NOT NULL CHECK (
    scope IN (
      'development',
      'preview',
      'verification',
      'deployment',
      'shared'
    )
  ),

  encrypted_value TEXT NOT NULL,

  key_version INTEGER NOT NULL DEFAULT 1,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (
    user_id,
    project_id,
    name,
    scope
  )
);


ALTER TABLE public.project_runtime_revisions
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.project_runtime_sessions
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.project_runtime_events
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.project_runtime_secrets
  ENABLE ROW LEVEL SECURITY;


DO $$
BEGIN

  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'project_runtime_revisions'
      AND policyname = 'Users read own project runtime revisions'
  ) THEN
    CREATE POLICY "Users read own project runtime revisions"
      ON public.project_runtime_revisions
      FOR SELECT
      USING (
        auth.uid() = user_id
      );
  END IF;


  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'project_runtime_sessions'
      AND policyname = 'Users read own project runtime sessions'
  ) THEN
    CREATE POLICY "Users read own project runtime sessions"
      ON public.project_runtime_sessions
      FOR SELECT
      USING (
        auth.uid() = user_id
      );
  END IF;


  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'project_runtime_events'
      AND policyname = 'Users read own project runtime events'
  ) THEN
    CREATE POLICY "Users read own project runtime events"
      ON public.project_runtime_events
      FOR SELECT
      USING (
        auth.uid() = user_id
      );
  END IF;

END $$;


GRANT ALL
  ON TABLE public.project_runtime_revisions
  TO service_role;

GRANT ALL
  ON TABLE public.project_runtime_sessions
  TO service_role;

GRANT ALL
  ON TABLE public.project_runtime_events
  TO service_role;

GRANT ALL
  ON TABLE public.project_runtime_secrets
  TO service_role;


GRANT SELECT
  ON TABLE public.project_runtime_revisions
  TO authenticated;

GRANT SELECT
  ON TABLE public.project_runtime_sessions
  TO authenticated;

GRANT SELECT
  ON TABLE public.project_runtime_events
  TO authenticated;

-- Deliberately NO authenticated SELECT grant for
-- project_runtime_secrets.
--
-- Decryption is server-only.
