/** 92 features unlocked on every Xroga plan */
export const XROGA_FEATURES = [
  'Multi-agent Swarm (Architect·Builder·Reviewer·QA)',
  'GitHub push & Vercel deploy',
  'Xroga Safe Browser (zero adult content)',
  '710+ integrations catalog',
  'GitHub connect & deploy',
  'Honest action-based billing',
  'Reverse action calculator',
  'Terminal fullscreen mode',
  'Split terminal + browser view',
  'Theme: Image / White / Black / Gray',
  'Terminal skin cycling',
  'Voice input (mic)',
  'File upload (any format)',
  'Drag & drop attachments',
  'Project file manager',
  'Swarm run history',
  'Build run history',
  'Build history',
  'Action spend analytics',
  'Custom domain deploy',
  'Vercel deploy hook',
  'Website generation',
  'Expo Android/iOS app scaffold',
  'User-owned publish (Vercel + Expo/EAS)',
  'Encrypted Expo / store credential vault',
  'Next.js auth + API scaffold',
  '3D/2D game builds',
  'Image generation',
  'Creative writing scripts',
  'Web search & research',
  'Code debug & fix',
  '3D model generation',
  'Voice TTS & cloning',
  'API key vault',
  'Custom webhooks',
  'Slack integration (UI)',
  'Discord integration (UI)',
  'Notion integration (UI)',
  'Stripe billing',
  'PayPal billing',
  'Top-up actions',
  'Free trial 50 actions',
  'Concurrency limits per plan',
  'Real-time SSE swarm stream',
  'Truth Council verification',
  'Out-of-actions modal',
  'Notification bell',
  'Profile & avatar upload',
  'Settings & preferences',
  'Sidebar search',
  'Media gallery',
  'Quick action tabs',
  'Homepage prompt carry-over',
  'Magic link auth',
  'Google OAuth',
  'GitHub OAuth',
  'Email/password auth',
  'Privacy-first safe search',
  'VPN/proxy detection (browser)',
  'URL category blocklist',
  'Forced SafeSearch on queries',
  'Tab isolation (browser)',
  'Download scan (browser)',
  'Swarm message typewriter',
  'AI response branding',
  'Compact analytics',
  'Integration search',
  'Custom credentials store',
  'Plan upgrade flow',
  'Galactic pricing tiers',
  'About & CEO page',
  'SEO sitemap & robots',
  'OpenGraph meta tags',
  'Mobile responsive shell',
  'Collapsible sidebar',
  'Resizable sidebar',
  'Hover tips & guides',
  'Dashboard terminal dock',
  'Chat integrations bar',
  'GitHub repo picker',
  'Action cost modal',
  'Cost estimate per prompt',
  'Activity feed',
  'Billing management',
  'Security settings tab',
  'Theme custom wallpapers',
  'Desktop + mobile backgrounds',
  'Pro upgrade CTA',
  'Mini action meter',
  'Header action meter',
  'Continue build runs',
  'Running/failed build filters',
  'Project detail view',
  'File preview',
  'Chats / swarm history',
  'Placeholder security page',
  'Middleware auth guard',
  'Fly.io API backend',
  'Supabase auth & profiles',
];

export const FEATURE_COUNT = XROGA_FEATURES.length;
