/** Honest feature list — only capabilities that ship today (no retired media/browser studio). */
export const XROGA_FEATURES = [
  'Black Hole V∞ coding agent',
  'Converter → Builder → QA → Ship loop',
  'Sticky GitHub repo (create + iterate)',
  'Vercel deploy on your account',
  'Optional Supabase keys in vault → Vercel env',
  'Expo Android/iOS app scaffold',
  'One-click EAS trigger on your Expo account',
  'Encrypted Expo / store credential vault',
  'Chrome extension (MV3) scaffold + zip',
  'Electron desktop scaffold + GitHub Releases',
  'Next.js auth + API scaffold',
  'Crypto market dashboard pack (no custody/trading)',
  'Automation agent runner scaffold (cron/LLM)',
  'Web + X live research (when keyed)',
  'Code debug & fix',
  'Website & SaaS generation',
  '710+ integrations catalog',
  'Honest token-based billing',
  'Relative complexity estimator',
  'Terminal fullscreen mode',
  'Split terminal + browser preview',
  'Theme: White / Black / Gray',
  'Voice input (dictate) + Talk with Xroga AI',
  'File upload & drag-drop attachments',
  'Project file manager',
  'Swarm / build run history',
  'Token spend analytics',
  'Custom domain deploy (your Vercel)',
  'Real-time SSE swarm stream',
  '~0.55M free trial tokens',
  'Concurrency limits per plan',
  'Plan upgrades (Lemon Squeezy)',
  'Magic link / Google / GitHub / email auth',
  'Profile & settings',
  'Mobile responsive Workspace',
  'SEO sitemap & OpenGraph',
  'Fly.io API backend',
  'Supabase auth & profiles',
];

export const FEATURE_COUNT = XROGA_FEATURES.length;
