/** Honest feature list — only capabilities that ship today (no retired media/browser studio). */
export const XROGA_FEATURES = [
  'Black Hole V∞ coding agent',
  'Converter → Builder → QA → Ship loop',
  'Sticky GitHub repo (create + iterate)',
  'Vercel deploy on your account',
  'Optional Supabase keys in vault → Vercel env',
  'Expo Android/iOS scaffold → GitHub (EAS via Publish + your token)',
  'Encrypted Expo / store credential vault (handoff — not auto store submit)',
  'Chrome extension (MV3) → GitHub Releases zip',
  'Electron desktop → GitHub Actions release (wait for zip)',
  'Next.js auth + API scaffold',
  'Crypto market dashboard pack (no custody/trading)',
  'Automation agent runner scaffold (cron/LLM)',
  'Web + X live research (when keyed)',
  'Code debug & fix',
  'Website & SaaS generation',
  'Chatbot landing + BYOK /api/chat scaffold',
  'Ship GitHub → Vercel (web) / Releases (Chrome & desktop)',
  'Connectable: GitHub, Vercel, Supabase, Expo, billing keys',
  'Honest token-based billing',
  'Terminal fullscreen mode',
  'Browser preview dock',
  'Theme: White / Black / Gray',
  'Voice input (dictate) + Talk with Xroga AI',
  'File upload & drag-drop attachments',
  'Project file manager',
  'Swarm / build run history',
  'Token spend analytics',
  'Custom domain deploy (your Vercel)',
  'Real-time SSE swarm stream',
  '~0.55M free trial tokens',
  'Concurrency limits per plan',
  'Plan upgrades (Lemon Squeezy)',
  'Magic link / Google / GitHub / email auth',
  'Profile & settings',
  'Mobile responsive Workspace',
  'SEO sitemap & OpenGraph',
  'Fly.io API backend',
  'Supabase auth & profiles',
];

export const FEATURE_COUNT = XROGA_FEATURES.length;
