/** Auto-generated by scripts/generate-integrations-catalog.mjs — do not edit by hand */
import type { Integration } from './integrations';

export const INTEGRATION_CATALOG_CATEGORIES = [
  "Developer & Code",
  "Gaming & Consoles",
  "Social Media & Communication",
  "E-commerce & Payments",
  "AI & Media APIs",
  "Automation & Scraping",
  "Monitoring & Analytics",
  "Marketing & Email",
  "File & Storage",
  "Cloud & Infrastructure",
  "Databases & Data Stores",
  "Project Management & Collaboration",
  "Identity & Security",
  "CMS & Headless Content",
  "Finance & Banking",
  "Shipping & Logistics",
  "Customer Support & HR",
  "Education & Learning",
  "Data Platforms & CDP",
  "Real Estate & Construction",
  "Healthcare & Medical",
  "Energy, Agriculture & Environment",
  "Industrial, Mining & Manufacturing",
  "Space, Aviation & Maritime",
  "Government & National Infrastructure",
  "Media, Entertainment & Sports",
  "Hospitality & Travel",
  "Startup & Investment",
  "Palestinian & Humanitarian Tech",
  "Food Tech & Restaurant Ops",
  "Fire, Emergency & Archives",
  "Domain & DNS",
  "Microsoft Ecosystem",
  "Calendar & Scheduling"
] as const;

export const INTEGRATION_CATALOG: Integration[] = [
  {
    "id": "github",
    "name": "GitHub",
    "category": "Developer & Code",
    "status": "connected",
    "oauth": true
  },
  {
    "id": "gitlab",
    "name": "GitLab",
    "category": "Developer & Code",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "vercel",
    "name": "Vercel",
    "category": "Developer & Code",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "netlify",
    "name": "Netlify",
    "category": "Developer & Code",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "railway",
    "name": "Railway",
    "category": "Developer & Code",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "aws",
    "name": "AWS",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "digitalocean",
    "name": "DigitalOcean",
    "category": "Developer & Code",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "heroku",
    "name": "Heroku",
    "category": "Developer & Code",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "render",
    "name": "Render",
    "category": "Developer & Code",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "supabase",
    "name": "Supabase",
    "category": "Developer & Code",
    "status": "connected",
    "description": "Database, Auth, RLS"
  },
  {
    "id": "upstash_redis",
    "name": "Upstash Redis",
    "category": "Developer & Code",
    "status": "connected",
    "description": "Task queue & caching"
  },
  {
    "id": "circleci",
    "name": "CircleCI",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "buildkite",
    "name": "Buildkite",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "jenkins_cloudbees",
    "name": "Jenkins (CloudBees)",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "fly_io",
    "name": "Fly.io",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "coolify",
    "name": "Coolify",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "appwrite",
    "name": "Appwrite",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "qstash",
    "name": "QStash",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "tinybird",
    "name": "Tinybird",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "clickhouse",
    "name": "ClickHouse",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "sonarqube",
    "name": "SonarQube",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "snyk",
    "name": "Snyk",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "dependabot",
    "name": "Dependabot",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "launchdarkly",
    "name": "LaunchDarkly",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "docker_hub",
    "name": "Docker Hub",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "ghcr",
    "name": "GHCR",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "jfrog",
    "name": "JFrog",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "sonatype_nexus",
    "name": "Sonatype Nexus",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "npm",
    "name": "npm",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "pypi",
    "name": "PyPI",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "nuget",
    "name": "NuGet",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "hashnode",
    "name": "Hashnode",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "dev_to",
    "name": "DEV.to",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "medium",
    "name": "Medium",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "rapidapi",
    "name": "RapidAPI",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "postman",
    "name": "Postman",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "insomnia",
    "name": "Insomnia",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "hoppscotch",
    "name": "Hoppscotch",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "bruno",
    "name": "Bruno",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "swaggerhub",
    "name": "SwaggerHub",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "readme",
    "name": "ReadMe",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "stoplight",
    "name": "Stoplight",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "mockoon",
    "name": "Mockoon",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "wiremock",
    "name": "WireMock",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "github_copilot",
    "name": "GitHub Copilot",
    "category": "Developer & Code",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "replit",
    "name": "Replit",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "lovable",
    "name": "Lovable",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "bolt_new",
    "name": "Bolt.new",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "vercel_v0",
    "name": "Vercel v0",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "magic_patterns",
    "name": "Magic Patterns",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "databutton",
    "name": "Databutton",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "aider",
    "name": "Aider",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "composio",
    "name": "Composio",
    "category": "Developer & Code",
    "status": "not_connected"
  },
  {
    "id": "xbox_series_x_s_one",
    "name": "Xbox (Series X/S & One)",
    "category": "Gaming & Consoles",
    "status": "not_connected",
    "oauth": true,
    "description": "Xbox Store API — Series X|S & Xbox One"
  },
  {
    "id": "playstation_ps5_ps4",
    "name": "PlayStation (PS5 & PS4)",
    "category": "Gaming & Consoles",
    "status": "not_connected",
    "oauth": true,
    "description": "PlayStation Store — PS5 & PS4 unified API"
  },
  {
    "id": "steam_pc",
    "name": "Steam / PC",
    "category": "Gaming & Consoles",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "nintendo_switch",
    "name": "Nintendo Switch",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "epic_games",
    "name": "Epic Games",
    "category": "Gaming & Consoles",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "unity_gaming_services",
    "name": "Unity Gaming Services",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "roblox",
    "name": "Roblox",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "itch_io",
    "name": "itch.io",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "google_play_store",
    "name": "Google Play Store",
    "category": "Gaming & Consoles",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "microsoft_store",
    "name": "Microsoft Store",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "snap_store",
    "name": "Snap Store",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "flathub",
    "name": "Flathub",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "unity_cloud_devops",
    "name": "Unity Cloud / DevOps",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "unreal_engine_horde",
    "name": "Unreal Engine (Horde)",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "roblox_open_cloud",
    "name": "Roblox Open Cloud",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "fortnite_creative",
    "name": "Fortnite Creative",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "decentraland",
    "name": "Decentraland",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "vrchat",
    "name": "VRChat",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "sportradar",
    "name": "Sportradar",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "genius_sports",
    "name": "Genius Sports",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "bet365_api",
    "name": "Bet365 API",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "scientific_games_sg_digital",
    "name": "Scientific Games (SG Digital)",
    "category": "Gaming & Consoles",
    "status": "not_connected"
  },
  {
    "id": "twitter_x",
    "name": "Twitter/X",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "linkedin",
    "name": "LinkedIn",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "instagram",
    "name": "Instagram",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "facebook",
    "name": "Facebook",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "youtube",
    "name": "YouTube",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "tiktok",
    "name": "TikTok",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "gmail_google_calendar",
    "name": "Gmail / Google Calendar",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "outlook",
    "name": "Outlook",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "slack",
    "name": "Slack",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "discord",
    "name": "Discord",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "telegram",
    "name": "Telegram",
    "category": "Social Media & Communication",
    "status": "not_connected"
  },
  {
    "id": "whatsapp_business",
    "name": "WhatsApp Business",
    "category": "Social Media & Communication",
    "status": "not_connected"
  },
  {
    "id": "pinterest",
    "name": "Pinterest",
    "category": "Social Media & Communication",
    "status": "not_connected"
  },
  {
    "id": "zoom",
    "name": "Zoom",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "google_meet",
    "name": "Google Meet",
    "category": "Social Media & Communication",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "signal",
    "name": "Signal",
    "category": "Social Media & Communication",
    "status": "not_connected"
  },
  {
    "id": "threads_api",
    "name": "Threads API",
    "category": "Social Media & Communication",
    "status": "not_connected"
  },
  {
    "id": "meta_business_suite",
    "name": "Meta Business Suite",
    "category": "Social Media & Communication",
    "status": "not_connected"
  },
  {
    "id": "meta_pixel_conv_api",
    "name": "Meta Pixel (Conv. API)",
    "category": "Social Media & Communication",
    "status": "not_connected"
  },
  {
    "id": "stripe",
    "name": "Stripe",
    "category": "E-commerce & Payments",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "paypal",
    "name": "PayPal",
    "category": "E-commerce & Payments",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "paddle",
    "name": "Paddle",
    "category": "E-commerce & Payments",
    "status": "connected",
    "description": "Subscription billing"
  },
  {
    "id": "lemon_squeezy",
    "name": "Lemon Squeezy",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "binance",
    "name": "Binance",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "coinbase",
    "name": "Coinbase",
    "category": "E-commerce & Payments",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "alpaca",
    "name": "Alpaca",
    "category": "E-commerce & Payments",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "shopify",
    "name": "Shopify",
    "category": "E-commerce & Payments",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "woocommerce",
    "name": "WooCommerce",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "braintree",
    "name": "Braintree",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "adyen",
    "name": "Adyen",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "chargebee",
    "name": "Chargebee",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "recurly",
    "name": "Recurly",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "alchemy",
    "name": "Alchemy",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "moralis",
    "name": "Moralis",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "bigcommerce",
    "name": "BigCommerce",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "magento_adobe_commerce",
    "name": "Magento (Adobe Commerce)",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "printful",
    "name": "Printful",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "printify",
    "name": "Printify",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "gelato",
    "name": "Gelato",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "redbubble",
    "name": "Redbubble",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "teespring_spring",
    "name": "Teespring (Spring)",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "gooten",
    "name": "Gooten",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "lulu_direct",
    "name": "Lulu Direct",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "spod",
    "name": "SPOD",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "dsers",
    "name": "DSers",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "cj_dropshipping",
    "name": "CJ Dropshipping",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "zendrop",
    "name": "Zendrop",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "spocket",
    "name": "Spocket",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "modalyst",
    "name": "Modalyst",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "autods",
    "name": "AutoDS",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "square",
    "name": "Square",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "toast",
    "name": "Toast",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "clover",
    "name": "Clover",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "rakuten_advertising",
    "name": "Rakuten Advertising",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "shareasale",
    "name": "ShareASale",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "impact",
    "name": "Impact",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "grin",
    "name": "Grin",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "aspire",
    "name": "Aspire",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "commission_junction_cj",
    "name": "Commission Junction (CJ)",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "flexoffers",
    "name": "FlexOffers",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "pepperjam",
    "name": "Pepperjam",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "cin7",
    "name": "Cin7",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "brightpearl",
    "name": "Brightpearl",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "skubana_extensiv",
    "name": "Skubana (Extensiv)",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "halalwatch_api",
    "name": "HalalWatch API",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "alif_api",
    "name": "Alif API",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "salaam_gateway_api",
    "name": "Salaam Gateway API",
    "category": "E-commerce & Payments",
    "status": "not_connected"
  },
  {
    "id": "replicate",
    "name": "Replicate",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "runway",
    "name": "Runway",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "elevenlabs",
    "name": "ElevenLabs",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "deepseek",
    "name": "DeepSeek",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "anthropic_claude",
    "name": "Anthropic Claude",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "openai",
    "name": "OpenAI",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "google_gemini",
    "name": "Google Gemini",
    "category": "AI & Media APIs",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "groq",
    "name": "Groq",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "hugging_face",
    "name": "Hugging Face",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "fal_ai",
    "name": "Fal.ai",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "luma",
    "name": "Luma",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "tripo",
    "name": "Tripo",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "midjourney",
    "name": "Midjourney",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "stability_ai",
    "name": "Stability AI",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "perplexity",
    "name": "Perplexity",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "cohere",
    "name": "Cohere",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "mistral_ai",
    "name": "Mistral AI",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "assemblyai",
    "name": "AssemblyAI",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "whisper",
    "name": "Whisper",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "langchain",
    "name": "LangChain",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "llamaindex",
    "name": "LlamaIndex",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "deepl_grammarly",
    "name": "DeepL / Grammarly",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "brave_search_api",
    "name": "Brave Search API",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "you_com_api",
    "name": "You.com API",
    "category": "AI & Media APIs",
    "status": "not_connected"
  },
  {
    "id": "apify",
    "name": "Apify",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "browserless",
    "name": "Browserless",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "firecrawl",
    "name": "Firecrawl",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "llamaparse",
    "name": "LlamaParse",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "exa_ai",
    "name": "Exa.ai",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "tavily",
    "name": "Tavily",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "bright_data",
    "name": "Bright Data",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "newsapi",
    "name": "NewsAPI",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "scrapingbee",
    "name": "ScrapingBee",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "scrapingant",
    "name": "ScrapingAnt",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "zyte",
    "name": "Zyte",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "puppeteer_service",
    "name": "Puppeteer (service)",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "playwright_service",
    "name": "Playwright (service)",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "oxylabs",
    "name": "Oxylabs",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "smartproxy",
    "name": "Smartproxy",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "zapier",
    "name": "Zapier",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "make_integromat",
    "name": "Make (Integromat)",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "n8n",
    "name": "n8n",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "pipedream",
    "name": "Pipedream",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "boomi",
    "name": "Boomi",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "workato",
    "name": "Workato",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "mulesoft_anypoint",
    "name": "MuleSoft (Anypoint)",
    "category": "Automation & Scraping",
    "status": "not_connected"
  },
  {
    "id": "sentry",
    "name": "Sentry",
    "category": "Monitoring & Analytics",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "logrocket",
    "name": "LogRocket",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "posthog",
    "name": "PostHog",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "mixpanel",
    "name": "Mixpanel",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "google_analytics",
    "name": "Google Analytics",
    "category": "Monitoring & Analytics",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "segment",
    "name": "Segment",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "amplitude",
    "name": "Amplitude",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "heap",
    "name": "Heap",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "fullstory",
    "name": "FullStory",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "hotjar",
    "name": "Hotjar",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "metabase",
    "name": "Metabase",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "looker",
    "name": "Looker",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "new_relic",
    "name": "New Relic",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "datadog",
    "name": "Datadog",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "bugsnag",
    "name": "Bugsnag",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "prometheus",
    "name": "Prometheus",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "grafana",
    "name": "Grafana",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "dynatrace",
    "name": "Dynatrace",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "tableau",
    "name": "Tableau",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "power_bi",
    "name": "Power BI",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "ahrefs",
    "name": "Ahrefs",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "semrush",
    "name": "SEMrush",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "moz",
    "name": "Moz",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "integral_ad_science_ias",
    "name": "Integral Ad Science (IAS)",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "doubleverify",
    "name": "DoubleVerify",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "google_ads_api",
    "name": "Google Ads API",
    "category": "Monitoring & Analytics",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "microsoft_advertising",
    "name": "Microsoft Advertising",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "linkedin_ads",
    "name": "LinkedIn Ads",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "pinterest_ads",
    "name": "Pinterest Ads",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "snapchat_ads",
    "name": "Snapchat Ads",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "reddit_ads",
    "name": "Reddit Ads",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "tiktok_ads",
    "name": "TikTok Ads",
    "category": "Monitoring & Analytics",
    "status": "not_connected"
  },
  {
    "id": "sendgrid",
    "name": "SendGrid",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "resend",
    "name": "Resend",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "mailchimp",
    "name": "Mailchimp",
    "category": "Marketing & Email",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "convertkit",
    "name": "ConvertKit",
    "category": "Marketing & Email",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "hubspot",
    "name": "HubSpot",
    "category": "Marketing & Email",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "klaviyo",
    "name": "Klaviyo",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "activecampaign",
    "name": "ActiveCampaign",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "drip",
    "name": "Drip",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "salesforce",
    "name": "Salesforce",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "zoho_crm",
    "name": "Zoho CRM",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "twilio_standalone",
    "name": "Twilio (standalone)",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "postmark",
    "name": "Postmark",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "messagebird",
    "name": "MessageBird",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "canva",
    "name": "Canva",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "adobe_creative_cloud_api",
    "name": "Adobe Creative Cloud API",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "cloudinary",
    "name": "Cloudinary",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "bynder",
    "name": "Bynder",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "widen",
    "name": "Widen",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "bitly",
    "name": "Bitly",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "rebrandly",
    "name": "Rebrandly",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "dub_co",
    "name": "Dub.co",
    "category": "Marketing & Email",
    "status": "not_connected"
  },
  {
    "id": "cloudflare_r2",
    "name": "Cloudflare R2",
    "category": "File & Storage",
    "status": "connected",
    "description": "Object storage"
  },
  {
    "id": "aws_s3",
    "name": "AWS S3",
    "category": "File & Storage",
    "status": "not_connected"
  },
  {
    "id": "google_cloud_storage",
    "name": "Google Cloud Storage",
    "category": "File & Storage",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "dropbox",
    "name": "Dropbox",
    "category": "File & Storage",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "onedrive",
    "name": "OneDrive",
    "category": "File & Storage",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "backblaze_b2",
    "name": "Backblaze B2",
    "category": "File & Storage",
    "status": "not_connected"
  },
  {
    "id": "wasabi",
    "name": "Wasabi",
    "category": "File & Storage",
    "status": "not_connected"
  },
  {
    "id": "box",
    "name": "Box",
    "category": "File & Storage",
    "status": "not_connected"
  },
  {
    "id": "sharepoint",
    "name": "SharePoint",
    "category": "File & Storage",
    "status": "not_connected"
  },
  {
    "id": "cloudconvert",
    "name": "CloudConvert",
    "category": "File & Storage",
    "status": "not_connected"
  },
  {
    "id": "pdf_co",
    "name": "PDF.co",
    "category": "File & Storage",
    "status": "not_connected"
  },
  {
    "id": "gcp",
    "name": "GCP",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "azure",
    "name": "Azure",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "cloudflare_workers_dns",
    "name": "Cloudflare (Workers/DNS)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "hetzner",
    "name": "Hetzner",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "vultr",
    "name": "Vultr",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "terraform_cloud_hashicorp",
    "name": "Terraform Cloud (HashiCorp)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "ansible_awx",
    "name": "Ansible (AWX)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "localstack",
    "name": "LocalStack",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "teleport",
    "name": "Teleport",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "tailscale",
    "name": "Tailscale",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "zerotier",
    "name": "ZeroTier",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "ngrok",
    "name": "ngrok",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "cloudflare_tunnel",
    "name": "Cloudflare Tunnel",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "cloud_shells_bundle",
    "name": "Cloud Shells (bundle)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "traefik_hub",
    "name": "Traefik Hub",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "nginx_nms_f5_api",
    "name": "Nginx (NMS / F5 API)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "caddy_server_api",
    "name": "Caddy Server (API)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "kong",
    "name": "Kong",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "tyk",
    "name": "Tyk",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "hasura",
    "name": "Hasura",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "gravitee",
    "name": "Gravitee",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "fastly",
    "name": "Fastly",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "akamai_edge_security",
    "name": "Akamai (Edge & Security)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "kentik",
    "name": "Kentik",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "thousandeyes_cisco",
    "name": "ThousandEyes (Cisco)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "telegeography",
    "name": "TeleGeography",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "ripe_ncc_arin_apis",
    "name": "RIPE NCC / ARIN APIs",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "icann_zone_data",
    "name": "ICANN (Zone Data)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "peeringdb",
    "name": "PeeringDB",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "netbox",
    "name": "NetBox",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "oci_oracle_cloud",
    "name": "OCI (Oracle Cloud)",
    "category": "Cloud & Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "mongodb_atlas",
    "name": "MongoDB Atlas",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "neon",
    "name": "Neon",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "planetscale",
    "name": "PlanetScale",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "redis_enterprise",
    "name": "Redis Enterprise",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "confluent_kafka",
    "name": "Confluent (Kafka)",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "snowflake",
    "name": "Snowflake",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "databricks",
    "name": "Databricks",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "fivetran",
    "name": "Fivetran",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "airbyte",
    "name": "Airbyte",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "stitch",
    "name": "Stitch",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "dbt_data_build_tool",
    "name": "dbt (Data Build Tool)",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "algolia",
    "name": "Algolia",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "meilisearch",
    "name": "Meilisearch",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "typesense",
    "name": "Typesense",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "elastic_elk",
    "name": "Elastic (ELK)",
    "category": "Databases & Data Stores",
    "status": "not_connected"
  },
  {
    "id": "jira",
    "name": "Jira",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "linear",
    "name": "Linear",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "asana",
    "name": "Asana",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "trello",
    "name": "Trello",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "notion",
    "name": "Notion",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "figma",
    "name": "Figma",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "miro",
    "name": "Miro",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "airtable",
    "name": "Airtable",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "atlassian_confluence",
    "name": "Atlassian Confluence",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "atlassian_bitbucket",
    "name": "Atlassian Bitbucket",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "smartsheet_government_edition",
    "name": "Smartsheet (Government Edition)",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "studiobinder",
    "name": "StudioBinder",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "filmtrack",
    "name": "FilmTrack",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "shotgrid_autodesk",
    "name": "ShotGrid (Autodesk)",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "syncsketch",
    "name": "SyncSketch",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "scenechronize",
    "name": "Scenechronize",
    "category": "Project Management & Collaboration",
    "status": "not_connected"
  },
  {
    "id": "auth0",
    "name": "Auth0",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "okta",
    "name": "Okta",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "onelogin",
    "name": "OneLogin",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "clerk",
    "name": "Clerk",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "hashicorp_vault",
    "name": "HashiCorp Vault",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "vanta",
    "name": "Vanta",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "drata",
    "name": "Drata",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "secureframe",
    "name": "Secureframe",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "cloudflare_turnstile",
    "name": "Cloudflare Turnstile",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "hcaptcha",
    "name": "hCaptcha",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "mandiant_google_cloud",
    "name": "Mandiant (Google Cloud)",
    "category": "Identity & Security",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "recorded_future",
    "name": "Recorded Future",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "crowdstrike_falcon",
    "name": "CrowdStrike Falcon",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "zscaler_zero_trust",
    "name": "Zscaler (Zero Trust)",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "palo_alto_networks_cortex_xsoar",
    "name": "Palo Alto Networks (Cortex XSOAR)",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "anomali_threatconnect",
    "name": "Anomali / ThreatConnect",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "cisa_known_exploited_vulnerabilities",
    "name": "CISA (Known Exploited Vulnerabilities)",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "shodan_enterprise",
    "name": "Shodan (Enterprise)",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "virustotal",
    "name": "VirusTotal",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "onetrust",
    "name": "OneTrust",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "osano",
    "name": "Osano",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "scamadviser",
    "name": "ScamAdviser",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "sift",
    "name": "Sift",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "riskified",
    "name": "Riskified",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "forter",
    "name": "Forter",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "signifyd",
    "name": "Signifyd",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "onfido",
    "name": "Onfido",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "persona",
    "name": "Persona",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "jumio",
    "name": "Jumio",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "trulioo",
    "name": "Trulioo",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "veriff",
    "name": "Veriff",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "chainalysis",
    "name": "Chainalysis",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "elliptic",
    "name": "Elliptic",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "kisi",
    "name": "Kisi",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "openpath",
    "name": "Openpath",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "brivo",
    "name": "Brivo",
    "category": "Identity & Security",
    "status": "not_connected"
  },
  {
    "id": "contentful",
    "name": "Contentful",
    "category": "CMS & Headless Content",
    "status": "not_connected"
  },
  {
    "id": "sanity",
    "name": "Sanity",
    "category": "CMS & Headless Content",
    "status": "not_connected"
  },
  {
    "id": "wordpress",
    "name": "WordPress",
    "category": "CMS & Headless Content",
    "status": "not_connected"
  },
  {
    "id": "storyblok",
    "name": "Storyblok",
    "category": "CMS & Headless Content",
    "status": "not_connected"
  },
  {
    "id": "wix",
    "name": "Wix",
    "category": "CMS & Headless Content",
    "status": "not_connected"
  },
  {
    "id": "squarespace",
    "name": "Squarespace",
    "category": "CMS & Headless Content",
    "status": "not_connected"
  },
  {
    "id": "bubble",
    "name": "Bubble",
    "category": "CMS & Headless Content",
    "status": "not_connected"
  },
  {
    "id": "glide",
    "name": "Glide",
    "category": "CMS & Headless Content",
    "status": "not_connected"
  },
  {
    "id": "quickbooks_online",
    "name": "QuickBooks Online",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "xero",
    "name": "Xero",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "freshbooks",
    "name": "FreshBooks",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "plaid",
    "name": "Plaid",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "yapily",
    "name": "Yapily",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "tink",
    "name": "Tink",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "klarna",
    "name": "Klarna",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "affirm",
    "name": "Affirm",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "afterpay_clearpay",
    "name": "Afterpay (Clearpay)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "chargeback911",
    "name": "Chargeback911",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "ethoca_verifi",
    "name": "Ethoca / Verifi",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "dun_bradstreet_d_b",
    "name": "Dun & Bradstreet (D&B)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "experian_business_api",
    "name": "Experian Business API",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "creditsafe",
    "name": "Creditsafe",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "expensify",
    "name": "Expensify",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "ramp",
    "name": "Ramp",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "brex",
    "name": "Brex",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "marqeta",
    "name": "Marqeta",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "lithic",
    "name": "Lithic",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "unit",
    "name": "Unit",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "arab_financial_services_api",
    "name": "Arab Financial Services API",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "bank_of_palestine_api",
    "name": "Bank of Palestine API",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "liwwa_api",
    "name": "Liwwa API",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "sama_saudi_central_bank_apis",
    "name": "SAMA (Saudi Central Bank) APIs",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "egypt_meeza",
    "name": "Egypt Meeza",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "rentas_malaysia",
    "name": "RENTAS (Malaysia)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "bi_fast_bank_indonesia",
    "name": "BI-Fast (Bank Indonesia)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "buna_arab_monetary_fund",
    "name": "Buna (Arab Monetary Fund)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "ifs_islamic_financial_system",
    "name": "IFS (Islamic Financial System)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "sukuk_gateway_bloomberg",
    "name": "Sukuk Gateway (Bloomberg)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "thomson_reuters_eikon_islamic_finance",
    "name": "Thomson Reuters EIKON (Islamic Finance)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "wahed_invest",
    "name": "Wahed Invest",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "hdfc_islamic_window",
    "name": "HDFC (Islamic Window)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "la_riba_ameen_housing",
    "name": "La Riba / Ameen Housing",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "al_baraka_digital_banking",
    "name": "Al Baraka (Digital Banking)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "akhuwat",
    "name": "Akhuwat",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "kiva_interest_free",
    "name": "Kiva (Interest-Free)",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "ethis",
    "name": "Ethis",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "namafin",
    "name": "NamaFin",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "amana_funds",
    "name": "Amana Funds",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "yaqeen_fund_qardhasan_foundation",
    "name": "Yaqeen Fund / QardHasan Foundation",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "zoya_api",
    "name": "Zoya API",
    "category": "Finance & Banking",
    "status": "not_connected"
  },
  {
    "id": "shipstation",
    "name": "ShipStation",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "shippo",
    "name": "Shippo",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "easyship",
    "name": "Easyship",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "ups_api",
    "name": "UPS API",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "fedex_api",
    "name": "FedEx API",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "usps_api",
    "name": "USPS API",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "flexport",
    "name": "Flexport",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "freightos",
    "name": "Freightos",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "marinetraffic",
    "name": "MarineTraffic",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "vesselfinder",
    "name": "VesselFinder",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "port_of_rotterdam_api",
    "name": "Port of Rotterdam API",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "lufthansa_api",
    "name": "Lufthansa API",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "mawani_saudi_ports",
    "name": "Mawani (Saudi Ports)",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "dp_world_cargoes",
    "name": "DP World (CARGOES)",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "pakistan_single_window",
    "name": "Pakistan Single Window",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "kadin_indonesia",
    "name": "KADIN (Indonesia)",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "upu_api",
    "name": "UPU API",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "royal_mail_uk",
    "name": "Royal Mail (UK)",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "la_poste_france",
    "name": "La Poste (France)",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "deutsche_post_dhl",
    "name": "Deutsche Post DHL",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "pos_malaysia_pos_indonesia",
    "name": "Pos Malaysia / Pos Indonesia",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "saudi_post_spl",
    "name": "Saudi Post (SPL)",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "google_maps_platform",
    "name": "Google Maps Platform",
    "category": "Shipping & Logistics",
    "status": "not_connected",
    "oauth": true
  },
  {
    "id": "mapbox",
    "name": "Mapbox",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "here_technologies",
    "name": "Here Technologies",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "maxmind_geoip",
    "name": "MaxMind (GeoIP)",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "ipinfo",
    "name": "IPinfo",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "airmap_drone",
    "name": "Airmap (Drone)",
    "category": "Shipping & Logistics",
    "status": "not_connected"
  },
  {
    "id": "zendesk",
    "name": "Zendesk",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "intercom",
    "name": "Intercom",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "docusign",
    "name": "DocuSign",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "hellosign_dropbox_sign",
    "name": "HelloSign (Dropbox Sign)",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "gusto",
    "name": "Gusto",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "bamboohr",
    "name": "BambooHR",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "rippling",
    "name": "Rippling",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "ringcentral",
    "name": "RingCentral",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "aircall",
    "name": "Aircall",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "zoom_phone",
    "name": "Zoom Phone",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "twilio_flex",
    "name": "Twilio Flex",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "clio",
    "name": "Clio",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "lexisnexis",
    "name": "LexisNexis",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "sure_insurance_api",
    "name": "Sure (Insurance API)",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "bold_penguin",
    "name": "Bold Penguin",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "zocdoc",
    "name": "Zocdoc",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "goodrx_api",
    "name": "GoodRx API",
    "category": "Customer Support & HR",
    "status": "not_connected"
  },
  {
    "id": "canvas_instructure",
    "name": "Canvas (Instructure)",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "moodle",
    "name": "Moodle",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "blackboard",
    "name": "Blackboard",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "udemy_business",
    "name": "Udemy Business",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "coursera_for_business",
    "name": "Coursera for Business",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "applyboard",
    "name": "ApplyBoard",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "studyportals",
    "name": "Studyportals",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "envoy_global",
    "name": "Envoy Global",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "boundless_immigration",
    "name": "Boundless Immigration",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "gradright",
    "name": "GradRight",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "mpower_financing",
    "name": "MPOWER Financing",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "king_salman_global_academy_arabic_nlp",
    "name": "King Salman Global Academy (Arabic NLP)",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "qatar_foundation_al_jazeera_learning",
    "name": "Qatar Foundation / Al Jazeera Learning",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "minds_malaysia",
    "name": "MINDS (Malaysia)",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "tamer_institute_api",
    "name": "Tamer Institute API",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "archnet_api_islamic_architecture",
    "name": "ArchNet API (Islamic Architecture)",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "bushra_api_islamic_art",
    "name": "Bushra API (Islamic Art)",
    "category": "Education & Learning",
    "status": "not_connected"
  },
  {
    "id": "tealium",
    "name": "Tealium",
    "category": "Data Platforms & CDP",
    "status": "not_connected"
  },
  {
    "id": "blueconic",
    "name": "BlueConic",
    "category": "Data Platforms & CDP",
    "status": "not_connected"
  },
  {
    "id": "rudderstack",
    "name": "RudderStack",
    "category": "Data Platforms & CDP",
    "status": "not_connected"
  },
  {
    "id": "habu",
    "name": "Habu",
    "category": "Data Platforms & CDP",
    "status": "not_connected"
  },
  {
    "id": "infosum",
    "name": "InfoSum",
    "category": "Data Platforms & CDP",
    "status": "not_connected"
  },
  {
    "id": "svix",
    "name": "Svix",
    "category": "Data Platforms & CDP",
    "status": "not_connected"
  },
  {
    "id": "hookdeck",
    "name": "Hookdeck",
    "category": "Data Platforms & CDP",
    "status": "not_connected"
  },
  {
    "id": "appfolio",
    "name": "AppFolio",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "yardi",
    "name": "Yardi",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "procore",
    "name": "Procore",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "autodesk_construction_cloud",
    "name": "Autodesk Construction Cloud",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "zillow_api",
    "name": "Zillow API",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "redfin_api",
    "name": "Redfin API",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "corelogic",
    "name": "CoreLogic",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "plangrid_autodesk",
    "name": "PlanGrid (Autodesk)",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "oracle_primavera_p6",
    "name": "Oracle Primavera P6",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "trimble_tekla_structures",
    "name": "Trimble (Tekla Structures)",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "topcon_gnss",
    "name": "Topcon GNSS",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "leica_geosystems",
    "name": "Leica Geosystems",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "bentley_systems_itwin",
    "name": "Bentley Systems (iTwin)",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "autodesk_build",
    "name": "Autodesk Build",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "hcss",
    "name": "HCSS",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "assemble_systems",
    "name": "Assemble Systems",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "neom_digital_twin_api",
    "name": "NEOM (Digital Twin API)",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "masdar_city",
    "name": "Masdar City",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "kuwait_vision_2035_silk_city",
    "name": "Kuwait Vision 2035 (Silk City)",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "egypt_vision_2030_new_capital",
    "name": "Egypt Vision 2030 (New Capital)",
    "category": "Real Estate & Construction",
    "status": "not_connected"
  },
  {
    "id": "epic_systems_emr",
    "name": "Epic Systems (EMR)",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "cerner_oracle_health",
    "name": "Cerner (Oracle Health)",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "eclinicalworks",
    "name": "eClinicalWorks",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "dicom_pacs_systems",
    "name": "DICOM / PACS Systems",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "intuitive_surgical_da_vinci",
    "name": "Intuitive Surgical (Da Vinci)",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "change_healthcare",
    "name": "Change Healthcare",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "flatiron_health_roche",
    "name": "Flatiron Health (Roche)",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "veeva_vault",
    "name": "Veeva Vault",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "medidata_rave",
    "name": "Medidata Rave",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "dnanexus",
    "name": "DNAnexus",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "illumina_basespace",
    "name": "Illumina BaseSpace",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "oura_ring_api",
    "name": "Oura Ring API",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "fitbit_web_api",
    "name": "Fitbit Web API",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "garmin_connect",
    "name": "Garmin Connect",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "dexcom",
    "name": "Dexcom",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "withings",
    "name": "Withings",
    "category": "Healthcare & Medical",
    "status": "not_connected"
  },
  {
    "id": "john_deere_operations_center",
    "name": "John Deere Operations Center",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "climate_fieldview",
    "name": "Climate FieldView",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "taranis",
    "name": "Taranis",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "cropx",
    "name": "CropX",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "herddogg",
    "name": "HerdDogg",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "cropio",
    "name": "Cropio",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "climateai",
    "name": "ClimateAI",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "agrostar",
    "name": "AgroStar",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "syngenta_cropwise",
    "name": "Syngenta (CropWise)",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "silostop_api",
    "name": "Silostop API",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "enphase",
    "name": "Enphase",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "solaredge",
    "name": "SolarEdge",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "tesla_energy_api",
    "name": "Tesla Energy API",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "chargepoint",
    "name": "ChargePoint",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "gridx_griddy",
    "name": "GridX (Griddy)",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "schneider_electric_ecostruxure",
    "name": "Schneider Electric EcoStruxure",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "purpleair",
    "name": "PurpleAir",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "iqair",
    "name": "IQAir",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "usgs_earthquake_api",
    "name": "USGS Earthquake API",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "noaa_climate_api",
    "name": "NOAA Climate API",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "openweathermap",
    "name": "OpenWeatherMap",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "tomorrow_io",
    "name": "Tomorrow.io",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "scada_water_systems_aveva",
    "name": "SCADA Water Systems (AVEVA)",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "aquarius",
    "name": "Aquarius",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "goaigua",
    "name": "GoAigua",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "trimble_waterworks",
    "name": "Trimble WaterWorks",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "xylem_sensus",
    "name": "Xylem (Sensus)",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "dhi_mike",
    "name": "DHI MIKE",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "swcc_desalination",
    "name": "SWCC (Desalination)",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "kahramaa_qatar",
    "name": "Kahramaa (Qatar)",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "ibtci_jordan_water",
    "name": "IBTCI (Jordan Water)",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "hydration_watergen",
    "name": "Hydration (Watergen)",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "aquavolve",
    "name": "AquaVolve",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "katadyn_msr",
    "name": "Katadyn / MSR",
    "category": "Energy, Agriculture & Environment",
    "status": "not_connected"
  },
  {
    "id": "universal_robots_ur",
    "name": "Universal Robots (UR+)",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "boston_dynamics_spot_api",
    "name": "Boston Dynamics Spot API",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "octoprint",
    "name": "OctoPrint",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "sparkfun_datastream",
    "name": "SparkFun DataStream",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "fanuc_field_system",
    "name": "FANUC Field System",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "siemens_tia_portal",
    "name": "Siemens (TIA Portal)",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "ge_digital_apm",
    "name": "GE Digital (APM)",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "aspentech",
    "name": "AspenTech",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "flsmidth",
    "name": "FLSmidth",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "sap_s_4hana_manufacturing",
    "name": "SAP S/4HANA (Manufacturing)",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "maptek_vulcan",
    "name": "Maptek Vulcan",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "deswik",
    "name": "Deswik",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "micromine",
    "name": "Micromine",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "minesense",
    "name": "MineSense",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "abb_mining",
    "name": "ABB Mining",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "rio_tinto_mine_of_the_future",
    "name": "Rio Tinto (Mine of the Future)",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "caterpillar_minestar",
    "name": "Caterpillar (MineStar)",
    "category": "Industrial, Mining & Manufacturing",
    "status": "not_connected"
  },
  {
    "id": "inmarsat_api",
    "name": "Inmarsat API",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "iridium_edge",
    "name": "Iridium Edge",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "planet_labs_planet_api",
    "name": "Planet Labs (Planet API)",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "satellogic",
    "name": "Satellogic",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "spacex_starlink_api",
    "name": "SpaceX / Starlink API",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "nasa_open_apis",
    "name": "NASA Open APIs",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "copernicus_sentinels",
    "name": "Copernicus (Sentinels)",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "tesla_fleet_api",
    "name": "Tesla Fleet API",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "fordpass_connect",
    "name": "FordPass Connect",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "mercedes_benz_api",
    "name": "Mercedes-Benz API",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "smartcar",
    "name": "Smartcar",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "obd_ii_dongles",
    "name": "OBD-II Dongles",
    "category": "Space, Aviation & Maritime",
    "status": "not_connected"
  },
  {
    "id": "world_bank_open_data_api",
    "name": "World Bank Open Data API",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "imf_api",
    "name": "IMF API",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "un_comtrade_api",
    "name": "UN Comtrade API",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "customs_single_window_systems",
    "name": "Customs Single Window Systems",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "treasury_single_account_platforms",
    "name": "Treasury Single Account Platforms",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "national_ids_india_stack_mosip",
    "name": "National IDs (India Stack / MOSIP)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "sovereign_wealth_fund_platforms",
    "name": "Sovereign Wealth Fund Platforms",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "cubic_transportation_systems",
    "name": "Cubic Transportation Systems",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "siemens_mobility_api",
    "name": "Siemens Mobility API",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "citymapper",
    "name": "Citymapper",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "waze_carpool_api",
    "name": "Waze (Carpool API)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "palantir_foundry_government",
    "name": "Palantir Foundry (Government)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "esri_arcgis",
    "name": "Esri (ArcGIS)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "fema_api",
    "name": "FEMA API",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "gdacs",
    "name": "GDACS",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "terra_sentinel_copernicus_ems",
    "name": "Terra Sentinel (Copernicus EMS)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "everbridge",
    "name": "Everbridge",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "infralinx_ijglobal",
    "name": "Infralinx / IJGlobal",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "devex_development_finance",
    "name": "Devex (Development Finance)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "comesa_eco_trade_apis",
    "name": "COMESA / ECO Trade APIs",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "islamic_solidarity_fund_isfd",
    "name": "Islamic Solidarity Fund (ISFD)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "uae_pass",
    "name": "UAE Pass",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "absher_saudi_arabia",
    "name": "Absher (Saudi Arabia)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "tawakkalna_saudi",
    "name": "Tawakkalna (Saudi)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "nadra_pakistan",
    "name": "NADRA (Pakistan)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "mydigital_id_malaysia",
    "name": "MyDigital ID (Malaysia)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "eid_turkey",
    "name": "eID (Turkey)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "gcc_unified_visa",
    "name": "GCC Unified Visa",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "iraq_entry_jordanian_moi_api",
    "name": "Iraq Entry / Jordanian MoI API",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "nusuk_hajj_platform",
    "name": "Nusuk (Hajj Platform)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "makkah_route_initiative_api",
    "name": "Makkah Route Initiative API",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "hajj_smart_card",
    "name": "Hajj Smart Card",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "general_authority_two_holy_mosques",
    "name": "General Authority (Two Holy Mosques)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "zatca_zakat_tax",
    "name": "ZATCA (Zakat & Tax)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "department_of_waqf_uae",
    "name": "Department of Waqf (UAE)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "kuwait_awqaf_public_foundation",
    "name": "Kuwait Awqaf Public Foundation",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "saudi_aramco_digital",
    "name": "Saudi Aramco Digital",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "adnoc_spc",
    "name": "ADNOC (SPC)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "petronas_selangkah_api",
    "name": "Petronas (Selangkah API)",
    "category": "Government & National Infrastructure",
    "status": "not_connected"
  },
  {
    "id": "mux",
    "name": "Mux",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "vimeo_ott_api",
    "name": "Vimeo (OTT / API)",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "daily_co",
    "name": "Daily.co",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "comscore_box_office_api",
    "name": "Comscore Box Office API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "movielabs",
    "name": "MovieLabs",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "hudl",
    "name": "Hudl",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "catapult_sports",
    "name": "Catapult Sports",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "sleeper_api",
    "name": "Sleeper API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "espn_api",
    "name": "ESPN API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "fifa_api",
    "name": "FIFA API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "ioc_api",
    "name": "IOC API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "fiba",
    "name": "FIBA",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "world_athletics",
    "name": "World Athletics",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "f1_api",
    "name": "F1 API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "pga_tour_european_tour",
    "name": "PGA Tour / European Tour",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "atp_wta",
    "name": "ATP / WTA",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "fina",
    "name": "FINA",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "nba_api",
    "name": "NBA API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "nfl_api",
    "name": "NFL API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "mlb_api",
    "name": "MLB API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "uefa_api",
    "name": "UEFA API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "icc_api",
    "name": "ICC API",
    "category": "Media, Entertainment & Sports",
    "status": "not_connected"
  },
  {
    "id": "amadeus_hospitality",
    "name": "Amadeus (Hospitality)",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "siteminder",
    "name": "SiteMinder",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "oracle_opera_pms",
    "name": "Oracle Opera PMS",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "infor_hms",
    "name": "Infor HMS",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "availpro_mews",
    "name": "Availpro (Mews)",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "the_leading_hotels_of_the_world",
    "name": "The Leading Hotels of the World",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "jumeriah_group_api",
    "name": "Jumeriah Group API",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "halalbooking_api",
    "name": "HalalBooking API",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "adhan_api_prayer_times",
    "name": "Adhan API / Prayer Times",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "qurancloud_api",
    "name": "QuranCloud API",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "sunnah_com_api",
    "name": "Sunnah.com API",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "zabihah_api",
    "name": "Zabihah API",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "muslim_pro_api",
    "name": "Muslim Pro API",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "launchgood_api",
    "name": "LaunchGood API",
    "category": "Hospitality & Travel",
    "status": "not_connected"
  },
  {
    "id": "angellist",
    "name": "AngelList",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "republic",
    "name": "Republic",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "wefunder",
    "name": "Wefunder",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "crowdcube",
    "name": "Crowdcube",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "techstars_starview",
    "name": "Techstars (StarView)",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "innovate_uk_sbir_api",
    "name": "Innovate UK / SBIR API",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "aliph_capital_gcc",
    "name": "Aliph Capital (GCC)",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "apple_app_store_connect",
    "name": "Apple App Store Connect",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "sap",
    "name": "SAP",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "servicenow",
    "name": "ServiceNow",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "stack_overflow_for_teams",
    "name": "Stack Overflow for Teams",
    "category": "Startup & Investment",
    "status": "not_connected"
  },
  {
    "id": "gaza_sky_geeks",
    "name": "Gaza Sky Geeks",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "souktel",
    "name": "Souktel",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "humanitarian_openstreetmap_team_hot",
    "name": "Humanitarian OpenStreetMap Team (HOT)",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "akka_palestine_news_api",
    "name": "Akka (Palestine News API)",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "we_info",
    "name": "We.Info",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "aidtech_blockchain_for_refugees",
    "name": "AidTech (Blockchain for Refugees)",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "unrwa_digital_services_api",
    "name": "UNRWA Digital Services API",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "gofundme_api",
    "name": "GoFundMe API",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "donorbox",
    "name": "Donorbox",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "classy",
    "name": "Classy",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "globalgiving",
    "name": "GlobalGiving",
    "category": "Palestinian & Humanitarian Tech",
    "status": "not_connected"
  },
  {
    "id": "olo",
    "name": "Olo",
    "category": "Food Tech & Restaurant Ops",
    "status": "not_connected"
  },
  {
    "id": "squadle",
    "name": "Squadle",
    "category": "Food Tech & Restaurant Ops",
    "status": "not_connected"
  },
  {
    "id": "revel_systems",
    "name": "Revel Systems",
    "category": "Food Tech & Restaurant Ops",
    "status": "not_connected"
  },
  {
    "id": "firstdue",
    "name": "FirstDue",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "eso_emergency_services",
    "name": "ESO (Emergency Services)",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "alertsense_civicready",
    "name": "AlertSense (CivicReady)",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "wildfire_predictive_services",
    "name": "Wildfire Predictive Services",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "nfirs",
    "name": "NFIRS",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "securitas_g4s_fire_safety",
    "name": "Securitas / G4S (Fire & Safety)",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "internet_archive_api",
    "name": "Internet Archive API",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "library_of_congress_api",
    "name": "Library of Congress API",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "europeana_api",
    "name": "Europeana API",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "british_library_labs_api",
    "name": "British Library Labs API",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "unesco_world_heritage_api",
    "name": "UNESCO World Heritage API",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "dpla_api",
    "name": "DPLA API",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "qatar_national_library_api",
    "name": "Qatar National Library API",
    "category": "Fire, Emergency & Archives",
    "status": "not_connected"
  },
  {
    "id": "spaceship",
    "name": "Spaceship",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "godaddy",
    "name": "GoDaddy",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "namecheap",
    "name": "Namecheap",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "squarespace_domains",
    "name": "Squarespace Domains",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "name_com",
    "name": "Name.com",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "porkbun",
    "name": "Porkbun",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "hover",
    "name": "Hover",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "dynadot",
    "name": "Dynadot",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "gandi_net",
    "name": "Gandi.net",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "ionos",
    "name": "IONOS",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "dnsimple",
    "name": "DNSimple",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "ns1_ibm",
    "name": "NS1 (IBM)",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "akamai_edge_dns",
    "name": "Akamai Edge DNS",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "let_s_encrypt",
    "name": "Let's Encrypt",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "zerossl",
    "name": "ZeroSSL",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "digicert",
    "name": "DigiCert",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "sectigo",
    "name": "Sectigo",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "whoisxmlapi",
    "name": "WhoisXMLAPI",
    "category": "Domain & DNS",
    "status": "not_connected"
  },
  {
    "id": "azure_devops",
    "name": "Azure DevOps",
    "category": "Microsoft Ecosystem",
    "status": "not_connected"
  },
  {
    "id": "microsoft_graph_api",
    "name": "Microsoft Graph API",
    "category": "Microsoft Ecosystem",
    "status": "not_connected"
  },
  {
    "id": "power_automate",
    "name": "Power Automate",
    "category": "Microsoft Ecosystem",
    "status": "not_connected"
  },
  {
    "id": "power_apps",
    "name": "Power Apps",
    "category": "Microsoft Ecosystem",
    "status": "not_connected"
  },
  {
    "id": "calendly",
    "name": "Calendly",
    "category": "Calendar & Scheduling",
    "status": "not_connected"
  },
  {
    "id": "cal_com",
    "name": "Cal.com",
    "category": "Calendar & Scheduling",
    "status": "not_connected"
  },
  {
    "id": "savvycal",
    "name": "SavvyCal",
    "category": "Calendar & Scheduling",
    "status": "not_connected"
  },
  {
    "id": "oncehub",
    "name": "OnceHub",
    "category": "Calendar & Scheduling",
    "status": "not_connected"
  },
  {
    "id": "youcanbook_me",
    "name": "YouCanBook.me",
    "category": "Calendar & Scheduling",
    "status": "not_connected"
  },
  {
    "id": "cron_notion_calendar",
    "name": "Cron (Notion Calendar)",
    "category": "Calendar & Scheduling",
    "status": "not_connected"
  }
];
