/** Favicon / brand logo URLs for integrations — prefer local assets so logos never fail to load */
export const INTEGRATION_LOGOS: Record<string, string> = {
  github: '/brand/logos/github.svg',
  gitlab: '/brand/logos/gitlab.svg',
  vercel: '/brand/logos/vercel.svg',
  supabase: '/brand/logos/supabase.svg',
  openai: '/brand/logos/openai.svg',
  anthropic: '/brand/logos/anthropic.svg',
  gmail: 'https://cdn.simpleicons.org/gmail/EA4335',
  'google-calendar': 'https://cdn.simpleicons.org/googlecalendar/4285F4',
  'google-drive': 'https://cdn.simpleicons.org/googledrive/4285F4',
  slack: 'https://cdn.simpleicons.org/slack/4A154B',
  stripe: 'https://cdn.simpleicons.org/stripe/635BFF',
  shopify: 'https://cdn.simpleicons.org/shopify/7AB55C',
  hubspot: 'https://cdn.simpleicons.org/hubspot/FF7A59',
  notion: 'https://cdn.simpleicons.org/notion/000000',
  airtable: 'https://cdn.simpleicons.org/airtable/18BFFF',
  quickbooks: 'https://cdn.simpleicons.org/quickbooks/2CA01C',
  linear: 'https://cdn.simpleicons.org/linear/5E6AD2',
  sentry: 'https://cdn.simpleicons.org/sentry/362D59',
  brevo: 'https://cdn.simpleicons.org/brevo/0B996E',
  cloudflare: 'https://cdn.simpleicons.org/cloudflare/F38020',
  netlify: 'https://cdn.simpleicons.org/netlify/00C7B7',
  railway: 'https://cdn.simpleicons.org/railway/0B0D0E',
  aws: 'https://cdn.simpleicons.org/amazonaws/FF9900',
  digitalocean: 'https://cdn.simpleicons.org/digitalocean/0080FF',
  heroku: 'https://cdn.simpleicons.org/heroku/430098',
  render: 'https://cdn.simpleicons.org/render/000000',
  upstash_redis: 'https://cdn.simpleicons.org/upstash/00E9A3',
  paypal: 'https://cdn.simpleicons.org/paypal/00457C',
  lemon_squeezy: 'https://cdn.simpleicons.org/lemonsqueezy/FFC233',
  whop: 'https://cdn.simpleicons.org/whop/FF6243',
  gemini: 'https://cdn.simpleicons.org/googlegemini/8E75B2',
  discord: 'https://cdn.simpleicons.org/discord/5865F2',
  jira: 'https://cdn.simpleicons.org/jira/0052CC',
  asana: 'https://cdn.simpleicons.org/asana/F06A6A',
  trello: 'https://cdn.simpleicons.org/trello/0052CC',
  figma: 'https://cdn.simpleicons.org/figma/F24E1E',
  docker_hub: 'https://cdn.simpleicons.org/docker/2496ED',
  postman: 'https://cdn.simpleicons.org/postman/FF6C37',
  zapier: 'https://cdn.simpleicons.org/zapier/FF4A00',
  auth0: 'https://cdn.simpleicons.org/auth0/EB5424',
  datadog: 'https://cdn.simpleicons.org/datadog/632CA6',
  cloudflare_r2: 'https://cdn.simpleicons.org/cloudflare/F38020',
};


export function getIntegrationLogo(id: string): string | undefined {
  return INTEGRATION_LOGOS[id];
}
