import type { XrogaRichResult } from './xrogaRichResults';

/** Illustrative fixtures only. Never feed this module into production chat adapters. */
type Fixture = Omit<XrogaRichResult, 'status'>;
const image = (name: string, alt: string): NonNullable<Fixture['images']> => [{ url: `/os-preview/rich-results/${name}.webp`, alt, rights: 'demo-generated', attribution: 'Original AI-generated illustrative demo image' }];
const money = (amount: number, basis: NonNullable<Fixture['price']>['basis'], currency = 'USD'): Fixture['price'] => ({ amount, currency, basis, taxesIncluded: false, feesIncluded: false, note: 'Illustrative amount, not a current offer.' });
const fact = (label: string, value: string) => ({ label, value });
const flight = (from: string, to: string, departureLocal: string, arrivalLocal: string, departureTimeZone: string, arrivalTimeZone: string) => [{ from, to, departureLocal, arrivalLocal, departureTimeZone, arrivalTimeZone }];

const fixtures: Fixture[] = [
  { id: 'flight-sfo-dxb', domain: 'transport', kind: 'Flight example', transportMode: 'flight', title: 'San Francisco → Dubai', provider: 'Sample airline', summary: 'Illustrative long-haul flight card with distinct local times.', route: flight('SFO', 'DXB', '16:30', '19:15 +1 day', 'America/Los_Angeles', 'Asia/Dubai'), price: money(891, 'one-way'), images: image('airplane-window', 'Illustrative view from an airplane window'), facts: [fact('Stops', 'Nonstop'), fact('Class', 'Economy')] },
  { id: 'flight-multi', domain: 'transport', kind: 'Multi-leg flight example', transportMode: 'flight', title: 'San Francisco → London → Dubai', provider: 'Sample airlines', summary: 'Two connections shown separately; no real schedule or availability.', route: [...flight('SFO', 'LHR', '18:20', '12:40 +1 day', 'America/Los_Angeles', 'Europe/London'), ...flight('LHR', 'DXB', '16:10', '03:05 +1 day', 'Europe/London', 'Asia/Dubai')], price: money(760, 'one-way'), facts: [fact('Stops', '1 connection'), fact('Baggage', 'Not specified')] },
  { id: 'train', domain: 'transport', kind: 'Train example', transportMode: 'train', title: 'Zurich → Interlaken', provider: 'Sample rail provider', route: flight('Zürich HB', 'Interlaken Ost', '09:02', '10:55', 'Europe/Zurich', 'Europe/Zurich'), price: money(49, 'one-way', 'CHF'), facts: [fact('Class', '2nd class'), fact('Changes', '1')] },
  { id: 'bus', domain: 'transport', kind: 'Bus example', transportMode: 'bus', title: 'Paris → Brussels', provider: 'Sample bus provider', route: flight('Paris Bercy', 'Brussels Midi', '08:00', '12:10', 'Europe/Paris', 'Europe/Brussels'), price: money(28, 'one-way', 'EUR'), facts: [fact('Duration', '4h 10m')] },
  { id: 'ferry', domain: 'transport', kind: 'Ferry example', transportMode: 'ferry', title: 'Helsinki → Tallinn', provider: 'Sample ferry provider', route: flight('Helsinki', 'Tallinn', '10:30', '12:30', 'Europe/Helsinki', 'Europe/Tallinn'), price: money(34, 'one-way', 'EUR'), facts: [fact('Crossing', '2 hours')] },
  { id: 'transfer', domain: 'transport', kind: 'Transfer example', transportMode: 'transfer', title: 'Airport → city centre', provider: 'Sample transfer service', summary: 'Private transfer proposal, not booked.', price: money(55, 'one-way'), facts: [fact('Vehicle', 'Standard car'), fact('Passengers', 'Up to 3')] },
  { id: 'hotel-coast', domain: 'accommodation', kind: 'Hotel example', title: 'Coastal Suite', provider: 'Sample hotel', summary: 'Illustrative light-filled coastal room with a flexible sample rate.', images: image('coastal-suite', 'Illustrative coastal hotel suite'), price: money(210, 'per-night'), facts: [fact('Location', 'Coastal town'), fact('Room', '1 king bed'), fact('Cancellation', 'Not specified')] },
  { id: 'hotel-city', domain: 'accommodation', kind: 'Hotel example', title: 'City Studio', provider: 'Sample aparthotel', price: money(390, 'total-stay'), facts: [fact('Stay', '3 nights'), fact('Guests', '2 adults')] },
  { id: 'hostel', domain: 'accommodation', kind: 'Hostel example', title: 'Old Town Hostel', provider: 'Sample hostel', price: money(32, 'per-night', 'EUR'), facts: [fact('Room', 'Shared dorm'), fact('Breakfast', 'Not specified')] },
  { id: 'villa', domain: 'accommodation', kind: 'Villa example', title: 'Garden Villa', provider: 'Sample property host', images: image('coastal-suite', 'Illustrative interior, not a real villa photograph'), price: money(980, 'total-stay'), facts: [fact('Stay', '4 nights'), fact('Bedrooms', '2')] },
  { id: 'apartment', domain: 'accommodation', kind: 'Apartment example', title: 'Riverside Apartment', provider: 'Sample host', price: money(145, 'per-night'), facts: [fact('Bedrooms', '1'), fact('Kitchen', 'Yes')] },
  { id: 'headphones', domain: 'shopping', kind: 'Product example', title: 'Wireless Headphones', provider: 'Sample electronics seller', summary: 'Illustrative product image and price, not a real listing.', images: image('headphones', 'Illustrative unbranded over-ear headphones'), price: money(129, 'per-item'), facts: [fact('Color', 'Black'), fact('Stock', 'Not checked')] },
  { id: 'laptop', domain: 'shopping', kind: 'Product example', title: '13-inch Laptop', provider: 'Sample electronics seller', price: money(899, 'per-item'), facts: [fact('Memory', '16 GB'), fact('Storage', '512 GB'), fact('Stock', 'Not checked')] },
  { id: 'jacket', domain: 'shopping', kind: 'Clothing example', title: 'Weatherproof Jacket', provider: 'Sample apparel seller', price: money(119, 'per-item'), facts: [fact('Sizes', 'S–XL'), fact('Material', 'Recycled shell')] },
  { id: 'chair', domain: 'shopping', kind: 'Furniture example', title: 'Lounge Chair', provider: 'Sample furniture seller', price: money(240, 'per-item'), facts: [fact('Finish', 'Oak'), fact('Delivery', 'Not checked')] },
  { id: 'coupon-valid', domain: 'shopping', kind: 'Coupon example', title: 'Sample welcome discount', provider: 'Sample retailer', summary: 'For copy-button testing only; not a valid public code.', coupon: { code: 'DEMO-WELCOME', eligibility: 'Demo only; cannot be redeemed' }, facts: [fact('Discount', 'Illustrative 10%')] },
  { id: 'coupon-expired', domain: 'shopping', kind: 'Expired coupon example', title: 'Past seasonal promotion', provider: 'Sample retailer', coupon: { code: 'DEMO-EXPIRED', eligibility: 'Expired example' }, limitations: 'This demonstration coupon is expired and cannot be redeemed.' },
  { id: 'restaurant', domain: 'reservation', kind: 'Restaurant example', title: 'Neighborhood Bistro', provider: 'Sample restaurant', summary: 'Discovery result only; no table or time slot has been checked.', facts: [fact('Cuisine', 'Modern European'), fact('Area', 'City centre')] },
  { id: 'cafe', domain: 'reservation', kind: 'Café example', title: 'Corner Coffee', provider: 'Sample café', facts: [fact('Service', 'Coffee and bakery'), fact('Hours', 'Not checked')] },
  { id: 'appointment', domain: 'reservation', kind: 'Appointment example', title: 'Consultation visit', provider: 'Sample clinic', summary: 'Appointment options would require an authorized provider integration.', facts: [fact('Duration', '30 minutes'), fact('Time slots', 'Not checked')] },
  { id: 'event', domain: 'reservation', kind: 'Event ticket example', title: 'City design festival', provider: 'Sample venue', price: money(35, 'per-person'), facts: [fact('Date', 'Sample date only'), fact('Seat', 'Not assigned')] },
  { id: 'car', domain: 'vehicle', kind: 'Car rental example', title: 'Compact electric car', provider: 'Sample rental service', price: money(58, 'per-day'), facts: [fact('Seats', '5'), fact('Pickup', 'Airport'), fact('Insurance', 'Not specified')] },
  { id: 'van', domain: 'vehicle', kind: 'Van rental example', title: 'Cargo van', provider: 'Sample rental service', price: money(82, 'per-day'), facts: [fact('Capacity', '10 m³'), fact('Mileage', 'Not specified')] },
  { id: 'bike', domain: 'vehicle', kind: 'Bicycle rental example', title: 'City bicycle', provider: 'Sample bicycle shop', price: money(18, 'per-day'), facts: [fact('Helmet', 'Not specified')] },
  { id: 'alps', domain: 'travel', kind: 'Destination example', title: 'Swiss Alps escape', provider: 'Illustrative travel guide', summary: 'A destination card, not a package offer.', images: image('alpine-lake', 'Illustrative alpine lake and mountains'), facts: [fact('Theme', 'Mountains and lakes'), fact('Season', 'Varies')] },
  { id: 'itinerary', domain: 'travel', kind: 'Itinerary example', title: 'Three days in Lisbon', provider: 'Illustrative travel guide', facts: [fact('Day 1', 'Old town'), fact('Day 2', 'Waterfront'), fact('Day 3', 'Museums')] },
  { id: 'trail', domain: 'travel', kind: 'Trail example', title: 'Ridge walk', provider: 'Illustrative hiking guide', images: image('alpine-lake', 'Illustrative mountain landscape, not a trail map'), facts: [fact('Distance', '12 km'), fact('Difficulty', 'Moderate')] },
  { id: 'saas', domain: 'business', kind: 'Service example', title: 'Team planning software', provider: 'Sample software company', price: money(24, 'monthly'), facts: [fact('Seats', '5'), fact('Trial', 'Not checked')] },
  { id: 'agency', domain: 'business', kind: 'Agency example', title: 'Design agency', provider: 'Sample agency', facts: [fact('Focus', 'Brand and web'), fact('Location', 'Remote')] },
  { id: 'course', domain: 'other', kind: 'Course example', title: 'Introduction to typography', provider: 'Sample educator', price: money(89, 'total'), facts: [fact('Format', 'Self-paced'), fact('Duration', '4 weeks')] },
  { id: 'job', domain: 'other', kind: 'Job example', title: 'Frontend engineer', provider: 'Sample employer', facts: [fact('Location', 'Remote'), fact('Type', 'Full-time')] },
  { id: 'insurance', domain: 'other', kind: 'Insurance example', title: 'Travel coverage overview', provider: 'Sample insurer', facts: [fact('Coverage', 'Not verified'), fact('Terms', 'Provider document required')] },
  { id: 'delivery', domain: 'other', kind: 'Tracking example', title: 'Package status', provider: 'Sample carrier', facts: [fact('Latest state', 'Example only'), fact('Tracking ID', 'DEMO-0001')] },
];

export const RICH_RESULT_FIXTURES: XrogaRichResult[] = fixtures.map((item) => ({ ...item, status: 'demo' }));
